# def listaProductos():
#     print("Lista de productos")
#     print("1. Coca cola")
#     print("2. Cheetos")
#     print("3. Regresco")
#     print("4. Maruchan")
#     print("5. Palomitas")
#     print("6. Helado")
#     print("7. Mazapan")
#     print("8. Pastes")
#     print("9. Agua") 
#     print("10. Galletas") 

def Areas():
    print("1. Atencion al comrpibuyente")
    print("2. Recaudación")
    #print("Audiotria")
    #print("SRYS")


def Trabajadores():
    print("1.Valerya Hernandez Mendoza")
    print("2.Carlos García López")
    print("3.Sofia Martinez Ramirez")
    print("4.Alejandro Torres Medina")
    print("5.Ana Rodriguez Vargas")
    print("6.Laura Gonzalez Castro")
    print("7.Diego Morales Paredes")
    print("8.Isabella Herrera Cruz")
    print("9.Juan Silva Mendoza")
    print("10.Camila Rivera Guzmán")
    print("11.Andrés Ortega Jiménez")
    print("12.Valentina Torres Rosales")
    print("13.Sebastián Martinez Delgado")
    print("14.Lucía Gonzalez Reyes")
    print("15.Pedro Ramírez Bravo")
    print("16.Martina Paredes Castro")
    print("17.Francisco Sánchez Alvarado")
    print("18.Gabriela Morales Huerta")
    print("19.José Hernández Rosas")
    print("20.Natalia López Gómez")
    print("21.Aurora Gómez Montes")
    print("22.Mateo Hernández Velázquez")
    print("23.Sol Martínez Flores")
    print("24.Gabriel Nuñez Alvarado")
    print("25.Victoria Espinoza Ruiz")
    print("26.Lucas Méndez Torres")
    print("27.Alejandro Sánchez Bravo")
    print("28.Isabela Ortiz Méndez")
    print("29.Leonardo Fernández Núñez")
    print("30.Camila Ríos Paredes")

    
def Cita():
    print("Cuentas con cita?")
